apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: etvycq3qv-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: etvycq3qv-python 
  name: etvycq3qv-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: etvycq3qv-python 
